import { fal } from "@fal-ai/client";

// Configure fal.ai client with your API key
fal.config({
  credentials: process.env.FAL_KEY || '5e9fd9b9-b03d-480c-a9f7-2891fb40a256:9b16379200e6f53fe411d87a8c5c1135'
});

// Helper to upload base64 image to fal.ai storage
async function uploadBase64Image(base64String: string): Promise<string> {
  const base64Data = base64String.includes(',') 
    ? base64String.split(',')[1] 
    : base64String;

  // Convert base64 to blob
  const byteCharacters = atob(base64Data);
  const byteNumbers = new Array(byteCharacters.length);
  for (let i = 0; i < byteCharacters.length; i++) {
    byteNumbers[i] = byteCharacters.charCodeAt(i);
  }
  const byteArray = new Uint8Array(byteNumbers);
  const blob = new Blob([byteArray], { type: 'image/jpeg' });

  // Upload to fal.ai's storage
  const file = new File([blob], 'user-photo.jpg', { type: 'image/jpeg' });
  const uploadedUrl = await fal.storage.upload(file);
  
  return uploadedUrl;
}

export async function generateMoviePoster(
  posterUrl: string,
  userPhotoBase64: string,
  customPrompt: string // Changed from posterDescription to customPrompt
): Promise<string> {
  try {
    console.log('[FalService] Starting movie poster generation...');
    
    // Upload user photo to get a URL that fal.ai can access
    console.log('[FalService] Uploading user photo...');
    const userPhotoUrl = await uploadBase64Image(userPhotoBase64);
    console.log('[FalService] User photo uploaded:', userPhotoUrl);

    // Use the custom prompt from the database
    const prompt = customPrompt;
    console.log('[FalService] Using custom prompt:', prompt);

    console.log('[FalService] Calling Nano Banana Pro API...');
    
    // Call fal.ai Nano Banana Pro
    const result = await fal.subscribe("fal-ai/nano-banana-pro/edit", {
      input: {
        prompt: prompt,
        image_urls: [posterUrl, userPhotoUrl],
        num_images: 1,
        aspect_ratio: "auto",
        output_format: "png",
        resolution: "2K"
      },
      logs: true,
      onQueueUpdate: (update) => {
        if (update.status === "IN_PROGRESS") {
          update.logs?.map((log) => log.message).forEach(msg => {
            console.log('[FalService]', msg);
          });
        }
      },
    });

    console.log('[FalService] Generation complete!');

    // Extract the generated image URL
    if (result.data.images && result.data.images.length > 0) {
      const generatedImageUrl = result.data.images[0].url;
      console.log('[FalService] Generated image URL:', generatedImageUrl);
      
      // Fetch the image and convert to base64 for consistent return format
      const response = await fetch(generatedImageUrl);
      const blob = await response.blob();
      
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => {
          resolve(reader.result as string);
        };
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    }

    throw new Error("No image generated by fal.ai");
    
  } catch (error) {
    console.error("[FalService] Error generating poster:", error);
    throw error;
  }
}